-- WMS STOCKA - Supabase Schema: Creación de tabla para auditoría y registro de llamadas API Optiroute
-- Ejecuta este script en el SQL Editor de tu proyecto de Supabase.

CREATE TABLE IF NOT EXISTS optiroute_api_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
  source TEXT NOT NULL DEFAULT 'github_actions_cron',    -- 'github_actions_cron', 'frontend_support_ui', etc.
  merchant_id UUID,
  list_calls INTEGER DEFAULT 0,                           -- Peticiones HTTP al endpoint de listado paginado (/integration-service-requests/)
  detail_calls INTEGER DEFAULT 0,                         -- Peticiones HTTP de detalle individual (/integration-service-requests/{id}/)
  total_http_calls INTEGER DEFAULT 0,                     -- Suma total de peticiones HTTP a la API de Optiroute
  skipped_terminal INTEGER DEFAULT 0,                     -- Pedidos omitidos por estar en estado terminal (DELIVERED, CANCELLED, DELETED)
  skipped_unchanged INTEGER DEFAULT 0,                    -- Pedidos omitidos por no tener cambios en updated_at o estado
  orders_synced INTEGER DEFAULT 0,                        -- Pedidos guardados/actualizados en Supabase
  status TEXT DEFAULT 'normal',                            -- 'normal', 'warning', 'critical'
  details JSONB                                           -- Payload JSON con metadatos o errores de la corrida
);

-- Índice por fecha para consultas rápidas de métricas diarias
CREATE INDEX IF NOT EXISTS idx_optiroute_api_logs_created_at ON optiroute_api_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_optiroute_api_logs_status ON optiroute_api_logs(status);

-- Habilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE optiroute_api_logs ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad
DROP POLICY IF EXISTS "Admin puede gestionar logs de API Optiroute" ON optiroute_api_logs;
CREATE POLICY "Admin puede gestionar logs de API Optiroute" ON optiroute_api_logs
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM profiles 
      WHERE id = auth.uid() AND role IN ('admin', 'all')
    )
  );

DROP POLICY IF EXISTS "Permitir inserciones desde Service Role o anon si aplica" ON optiroute_api_logs;
CREATE POLICY "Permitir inserciones desde Service Role o anon si aplica" ON optiroute_api_logs
  FOR INSERT WITH CHECK (true);
